apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: aHlyMm1xNWs=
  CLOUDINARY_KEY: MTQ1MjgyNjgyMTgxNTQ1
  CLOUDINARY_SECRET: YjJoNVRtYVBnM19qbC1hdEZkYWJWd296blY1
  MAPBOX_TOKEN: aHpaWFptYkc5Nk1qVmpJbjAuUFNRNDR0VzZZbHpxRmZES2NrUzJHZw==
  DB_URL: bW9uZ29kYitzcnY6Ly8xOTAzMzAxNzVjc2VfZGJfdXNlcjpIamtibm0xMjk5MEBjbHVzdGVyMC51enRhMHM5Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw
